[".local/share/zinit/zinit.git"]
    type = "archive"
    url = "https://github.com/zdharma-continuum/zinit/archive/98d3eaa8beee3c650793b795e0f92ef1679d623e.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{- $asdfTags := output (printf "%s/.bin/asdf_latest_tag.bash" .chezmoi.sourceDir) -}}
{{- $asdfUrl := (first (fromJson $asdfTags)).tarball_url }}
[".asdf"]
    type = "archive"
    url = "{{ $asdfUrl }}"
    stripComponents = 1
[".local/share/node-build-update-defs"]
    type = "archive"
    url = "https://github.com/nodenv/node-build-update-defs/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{- $omnisharpReleaseAssets := (gitHubLatestRelease "OmniSharp/omnisharp-roslyn").Assets -}}
{{- $omnisharpAssetsName := "omnisharp-osx.tar.gz" -}}
{{- $omnisharpTarBall := "" -}}
{{- $root := . -}}
{{- range $omnisharpReleaseAssets -}}
  {{- if eq (.Name | lower) (ternary "omnisharp-osx.tar.gz" "omnisharp-linux-x86.tar.gz" (eq $root.chezmoi.os "darwin")) -}}
    {{- $omnisharpTarBall = .BrowserDownloadURL | trim -}}
  {{- end -}}
{{- end }}
[".local/share/omnisharp"]
    type = "archive"
    url = "{{ $omnisharpTarBall }}"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
