name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        shared: ["y", "n"]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -qq -y --no-install-recommends zsh shellcheck
    - name: Set zsh as default shell
      run: |
        sudo chsh -s $(which zsh) $(whoami)
    - name: Install chezmoi
      run: |
        sh -c "$(curl -fsLS git.io/chezmoi)"
    - name: Install dotfiles
      env:
        DOTFILES_EMAIL: info@example.com
        DOTFILES_SHARED_SERVER: ${{ matrix.shared }}
        DOTFILES_GPG_SIGNING_KEY: foo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./bin/chezmoi init --apply --source=.
    - name:
      run: |
        .bin/shellcheck_target.sh
